[package]
name = "railway-project-rs"
version = "0.1.0"
authors = ["Logarithmus <logarithmus.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
yarte = { version = "0.3", features = ["with-actix-web"] }
actix-web = { version = "1.0", default-features = false, features = ["rust-tls"] }
actix-rt = "0.2"
actix-files = "0.1"
serde = { version = "1.0", features = ["derive"] }
rustls = "*"
diesel = { version = "1.4", features = ["mysql", "chrono"] }
chrono = "0.4"